name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - arch: 'amd64'
            platform: 'x64'
          - arch: 'arm64'
            platform: 'ARM64'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: compnerd/gha-setup-vsdevenv@main
        with:
          host_arch: amd64
          arch: ${{ matrix.arch }}

      - name: Configure Sentry
        run: >
          cmake -B out `
                -D CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION=10.0.19041.0 `
                -G "Visual Studio 17 2022" `
                -A ${{ matrix.platform }} `
                -D CMAKE_SYSTEM_NAME=Windows `
                -D CMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} `
      - name: Build Sentry
        run: cmake --build out --config Release

      - name: Stage Sentry
        run: |
          New-Item -ItemType Directory -Path sentry-native\bin\win64 -Force | Out-Null
          New-Item -ItemType Directory -Path sentry-native\include -Force | Out-Null
          New-Item -ItemType Directory -Path sentry-native\lib\win64 -Force | Out-Null
          Copy-Item include\sentry.h sentry-native\include\
          Copy-Item out\Release\sentry.dll sentry-native\bin\win64\
          Copy-Item out\Release\sentry.lib sentry-native\lib\win64\

      - uses: actions/upload-artifact@v3
        with:
          name: sentry-native-windows-${{ matrix.arch }}
          path: sentry-native
